name: Level 2 Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NAME: Varsha

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show files
        run: ls

      - name: Print message
        run: echo "Hello $NAME 🚀"

      - name: Read HTML file
        run: cat index.html